### PR TITLE
Update Fish documentation (2.7.1)

### PR DESCRIPTION
**Pull request by maxnordlund**
It was relatively recently released https://fishshell.com/release_notes.html

### CODE REVIEW

**Comment by Thibaut** [comment]
Done in 6700c5e30c9f4a6c026dd63395bba1494736b181.

**Comment by maxnordlund** [comment]
I'm curious as to why you didn't just merge the PR?

**Comment by Thibaut** [comment]
Because this kind of PR is not useful, and the contributing guidelines specify not to submit those: https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#updating-existing-documentations

You didn't say if the scraper still works after the change, so this saves me no time. It's faster for me to do the update through my usual workflow. In the future you can request updates [here](https://trello.com/c/2B0hmW7M/52-request-updates-here) (or send PRs when those updates aren't straightforward).

**Comment by maxnordlund** [comment]
I see, well then i does make a bit more sense. You right, I din't verify the scraper, but as the website hadn't changed it's structure I figured it would work. Actually the docs for fish hasn't changed format in the years I've used it, which I find helpful for many reasons, scrapers included.

Next time a new contributor comes along and makes a (relatively) small misstake like this I gently suggest linking to the guidelines. It would have help me understand straight away instead of needing to ask.

Since this seems like something that a fair amount of people may trip on, do you think it should also be mentioned in the README? In that case I can make a PR updating it.

**Comment by Thibaut** [comment]
@maxnordlund You're right. Sorry I didn't provide an explanation.

> do you think it should also be mentioned in the README?

I'd rather keep all contributing guidelines in the CONTRIBUTING file, since it's linked in various places in the GitHub UI.

**Comment by maxnordlund** [comment]
True, but this is akin to a FAQ, so a bit of repetition may be prudent. Anyway, sounds good, and thanks for the apology I appreciate it.

**Pull request closed without merging**
