### PR TITLE
Feature/dlang

### PR DESCRIPTION
**Pull request by ANtlord**
Hello! I want to add support of [D language](http://dlang.org). I encountered 2 issues.
The first one is adding a syntax highlighting; I get PrismJS supports D language but I can't get how to enable the support for devdocs.
The second one is documentation source html files; I have it on my computer, I can't get how to pass them.

### CODE REVIEW

**Comment by wilzbach** [comment]
> The second one is documentation source html files; I have it on my computer, I can't get how to pass them.

How about using the docarchives?
They contain a snapshot of every dlang.org release:

https://github.com/wilzbach/dlang.org-archives

Btw there is a `docs.json` which is also used by Ddox and will probably be a lot easier to parse then scraping

**Comment by Thibaut** [comment]
Thanks for the PR. I'm on vacation for the next couple weeks. Aiming to work on this in early Sept (I have two other docs/PRs to do first).

> The first one is adding a syntax highlighting; I get PrismJS supports D language but I can't get how to enable the support for devdocs.

Don't worry about syntax highlighting. I'll take care of it. Please undo the change to `prism.js`.

>  The second one is documentation source html files; I have it on my computer, I can't get how to pass them.

This is intended. The doc files aren't part of the Git repository (the entire documentation content in DevDocs amount to 2GB and 150k files 😛). Please remove the change to `public/docs/docs.json`.

Lastly, please squash your commits so I can cherry-pick into `master` (fits my workflow better than merging on GitHub).

Have you tried to also include the [language reference](http://dlang.org/spec/spec.html) as part of the doc? To do that it may be easier to scrape http://dlang.org/ directly, rather than local files (i.e. using `UrlScraper` instead of `FileScraper`).

**Comment by ANtlord** [comment]
> Please remove the change to `public/docs/docs.json`.
No problem but it is changed after `thor docs:generate d --force`

**Comment by ANtlord** [comment]
> How about using the docarchives?
They contain a snapshot of every dlang.org release

It's ok, but I can't get how to implement mupliple version support. I don't see information about it on Devdocs wiki. @Thibaut Can you give me a link with information about that?

**Comment by Thibaut** [comment]
> > Please remove the change to `public/docs/docs.json`.
>
> No problem but it is changed after `thor docs:generate d --force`

You can leave the file changed but uncommitted. To remove the change from your commit, run these commands:
```
git checkout HEAD~ public/docs/docs.json
git add public/docs/docs.json
git commit --amend --reuse-message=HEAD
```
The first command resets the file to what it was before your commit (`HEAD` == the last commit). The next two amend that commit with the file reset.

> It's ok, but I can't get how to implement mupliple version support. I don't see information about it on Devdocs wiki. @Thibaut Can you give me a link with information about that?

Unfortunately there is no documentation for this, but if you look at the other scrapers, you'll see it's fairly straightforward. However for this PR I'd rather you keep it to a single version. I can take care of adding multi-version support after merging.

**Comment by ANtlord** [comment]
I've considered what you mentioned. Does the PR deserve to be in master branch?)

**Comment by Thibaut** [comment]
@ANtlord Thanks! If by "be in master branch" you mean "merged", then yes, I think this is ready to merge, but I haven't had time to try it yet, and it'll take some work to finish/polish the scraper. I just got back from vacation and aiming to merge all outstanding PRs in the next couple weeks.

**Comment by ANtlord** [comment]
Sorry. It was a bad metaphor. Thank for your review and I hope we will see the documentation in devdocs soon.

**Comment by Thibaut** [comment]
Done :)
bc8d9432c371a6483adaec7deccb3d8cefdc2374 8902d5331d997aa5ec4de326fec7020282280723
http://devdocs.io/d/

**Comment by ANtlord** [comment]
@Thibaut thanks a lot! But it seems the site site was changed during the merging. I will fix this. Also, I need to fix the url provides the documentation. Wait for a new PR.

**Comment by Thibaut** [comment]
@ANtlord good catch. I've made a bunch of improvements/fixes in 8225e1d7e63e78495f5aa85c31156feacf285703.

**Comment by ANtlord** [comment]
Thank you

**Pull request closed without merging**
