### PR TITLE
Add LÖVE Documentation

### PR DESCRIPTION
**Pull request by nucular**
Adds documentation for the [LÖVE game engine](https://love2d.org), licensed under the [GNU Free Documentation License 1.3](https://www.gnu.org/copyleft/fdl.html).

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks for the PR. Could you squash your commits please.

**Comment by nucular** [comment]
Sure, squashed everything.

**Comment by Thibaut** [comment]
Thanks. I'll try to get this out in the next 2-3 weeks.

**Comment by Thibaut** [comment]
Done: http://devdocs.io/love/ a25290de805051129863e1e6b3c98289defd132f e3582e267e24372fecd8eb9d4ba7b7d0feaa8afe

Great PR, thanks!

**Pull request closed without merging**
