### PR TITLE
Padrino 0 14 1

### PR DESCRIPTION
**Pull request by wikimatze**

### CODE REVIEW

**Comment by Thibaut** [comment]
Unfortunately the docs published at http://www.rubydoc.info/github/padrino/padrino-framework/ are still for v0.13.2, as indicated [here](http://www.rubydoc.info/github/padrino/padrino-framework/Padrino).

**Comment by Thibaut** [comment]
Closing, as this PR doesn't do much. Feel free to give me a ping if you notice that http://www.rubydoc.info/github/padrino/padrino-framework/ gets updated, and I'll get on this right away.

**Comment by wikimatze** [comment]
I'll do!

**Comment by wikimatze** [comment]
I'll trigger then, so that they will update it.

**Comment by wikimatze** [comment]
Hey, the pages are now updated. You can check http://www.rubydoc.info/find/gems?q=padrino and see that it is pointing to the latest `0.14.1.1` version. So you can now cherry-pick https://github.com/Thibaut/devdocs/pull/667/commits/82856787a83bb6f98a35096e16ac6ae8ec932a7b

**Comment by Thibaut** [comment]
@wikimatze thanks. Not sure I'll have time for updates this week-end, but this will be in the next release.

**Comment by wikimatze** [comment]
Should I create a new PR for the update?

**Comment by Thibaut** [comment]
@wikimatze Sorry I forgot to push my commits. I did the update last week-end.

**Comment by Thibaut** [comment]
ea20f6208a39d8af93465cafac1238ee3e6fe6f6

**Comment by wikimatze** [comment]
Awesome, thank you very much.

**Pull request closed without merging**
