### PR TITLE
Add Q.js documentation

### PR DESCRIPTION
**Pull request by elegantcoder**
Q.js documentation from https://github.com/kriskowal/q/wiki/API-Reference

### CODE REVIEW

**Comment by elegantcoder** [comment]
Hi, @Thibaut . I’m wondering how do you think about this PR, and waiting for your review.
To be honest I only have a slight understanding of what it going on here, so feel free to tell me about the code.

BTW - I love this awesome project!

**Comment by Thibaut** [comment]
Hi @elegantcoder. Sorry for not replying sooner and thanks for your contribution! I plan to get this merged either this week-end or the next.

**Comment by elegantcoder** [comment]
:+1:

**Comment by Thibaut** [comment]
Got busy with other things this week-end. Will merge this in a week.

**Comment by Thibaut** [comment]
Merged: a00e45e829b409f5db6fcc9e263a7ee02b99fd1c
Great work, thanks!

**Pull request closed without merging**
