### PR TITLE
add eslint doc (4.9.0)

### PR DESCRIPTION
**Pull request by clakech**

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks for the PR. Will get on this (and your other PR) as soon as I can.

**Comment by clakech** [comment]
Hello @Thibaut this PR has 1 month now 😄

**Comment by Thibaut** [comment]
@clakech There is only so much spare time I can spend on DevDocs without burning myself out. Getting pull requests like yours out is not as simple as hitting the merge button. It generally takes 30-90 minutes to polish & finish a PR that adds a new doc, all the while I also have to keep up with updates, issues, etc. I'm doing the best I can.

**Comment by j-f1** [comment]
> It generally takes 30-90 minutes to polish & finish a PR that adds a new doc

Have you considered documenting the steps you take so that we can do as much as we can in our PRs? For example, if you have a code style you follow, I’d be happy to set up some linters that ensure contributions follow it too. Also, if you could document the process you use to generate the icon spritesheets, contributors could include the updated spritesheet in PRs.

**Comment by clakech** [comment]
@Thibaut I know how hard maintaining open source is, that's why I wait for a month before a ping ;) don't burn yourself out, this projects is great but your life is more important for sure !

I don't want you to "just" to merge, I want that devdocs stay as stable and cool that it is now. I am a new contributor and not a ruby developer so I may have done some mistakes in my code for sure ^^ So let's polish this PR together.

If this doesn't land, I take it easy 🤷‍♂️ 

But how to contribute if you are the only one able to accept PR + you are too busy to accept some code proposal ? Maybe the community could help ? I would like to add some other documentations from AWS/Azure soon ;)

👍 with @j-f1

**Comment by Thibaut** [comment]
Done: 9fdaf078bdbae2074f6935b6321c5e1132155058 66d3228f766718fc7622dd3b784ce3e4306ee905
https://devdocs.io/eslint/

---

@j-f1 

> Have you considered documenting the steps you take so that we can do as much as we can in our PRs? For example, if you have a code style you follow, I’d be happy to set up some linters that ensure contributions follow it too. Also, if you could document the process you use to generate the icon spritesheets, contributors could include the updated spritesheet in PRs.

There aren't that many steps involved to get a new doc out (once the scraper is done and good). Things like updating the about page, changelog, icon sprite, etc. are easy. The hard part is to turn PRs/scrapers that kinda "just work" into properly formatted/styled/organized docs (which is a big part of DevDocs's value proposition, but also a lot of work).

You can see this in action in 66d3228f766718fc7622dd3b784ce3e4306ee905 and dac419289bea756e6b697c82572e5ebe028cceb3 (the scraper changes). I admit I could do a much better job with documentation, but unfortunately that also takes time, and I'm always running out of time :/

That said, if you're interested in contributing more actively to DevDocs, send me an email and we can discuss :)

---

@clakech 

> Maybe the community could help ?

I'm open to adding new contributors, but adding and updating docs isn't something that just about anyone can do. There's a lot to learn, and I want the quality of DevDocs to remain high. Community management and training are also time-consuming activities, which goes back to my catch-22 of not having enough time for everything :P 

One thing I'd like to eventually do, though, is move all the docs and metadata to an open service/registry, which would let anyone add/update documentations. This way contributors could push doc updates without requiring full access to everything, and relieve me of some of the maintenance burden.

> I would like to add some other documentations from AWS/Azure soon

Please try to make those PRs more polished than your first two (have a look at the follow-up commits I had for each one); it'll help getting them out faster.

**Pull request closed without merging**
