### PR TITLE
Add Phalcon documentation

### PR DESCRIPTION
**Pull request by hyjk2000**
Phalcon scraper sync with latest official documentation: https://docs.phalconphp.com/en/latest/

Syntax highlighting of official document is tricky to clean, still needs some work.

Hope you like this one. :smile:

### CODE REVIEW

**Comment by Thibaut** [comment]
Nice. Could you try to extract additional entries for each method of each class/interface?

**Comment by hyjk2000** [comment]
Oh yes. It's barely usable if I don't extract constants and methods. Now it's better.

**Comment by Thibaut** [comment]
Thanks. I'll merge & finish this in the coming weeks.

**Comment by Thibaut** [comment]
Merged: 
a812cc8d0a093735662bf7a5f9c99995d800ae61
4cde9d296176ab9ce85846890176c535897ba47c
ece7a75afdbfc0530bf3048f6e9d1e3bb3156df6

**Pull request closed without merging**
