### PR TITLE
Add scikit-image documentation

### PR DESCRIPTION
**Pull request by prashnts**
Added `scikit-image` docs from http://scikit-image.org/docs/0.12.x/api/api.html

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks for the PR. I'll try to get this out next week-end. In the meantime please squash your commits and revert the change to `docs.json`.

**Comment by prashnts** [comment]
I have squashed the commits. I can't figure how to revert changes to `docs.json`, which as far as I can see is `whitespace` -- tried rebasing. Would appreciate help there!

**Comment by Thibaut** [comment]
`git checkout HEAD~ public/docs/docs.json` then amending your commit (`git commit --amend`) should do it.

**Comment by Thibaut** [comment]
Done: 7f06c9c76eaf4585250a0347c3a9f1993a3078ba c8a21e90ed5f00c0ee27330d1edeed523702f52a http://devdocs.io/scikit_image/
Thanks for the PR!

**Pull request closed without merging**
