### PR TITLE
Update ruby.rb to get 2.2.1 documentation.

### PR DESCRIPTION
**Pull request by ab5124**
Changed the version to to the latest release of ruby.

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks but unless you've manually checked that the scraper still works, PRs like this aren't really helpful.
https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#updating-existing-documentations
I'll update the docs over the week-end.

**Comment by ab5124** [comment]
I verified by downloading the docs with Thor. Thanks for updating it though.

**Comment by Thibaut** [comment]
@ab5124 if you ran `thor docs:download ruby` that only fetches the 2.2.0 version I personally scraped and uploaded to DevDocs's server. To generate the docs you need to run `thor docs:generate`.

**Comment by ab5124** [comment]
Alright thanks for that information.  It fails with both 2.2.0 and 2.2.1 when trying to pull the docs from localhost.

**Pull request closed without merging**
