### PR TITLE
Adding documentation for elasticsearch

### PR DESCRIPTION
**Pull request by yosiat**
Hi,

I have added documentation for elasticsearch.

BTW - I really liked the architecture of devdocs :+1: !

### CODE REVIEW

**Comment by Thibaut** [comment]
Looks great, thanks!

I contacted Elastic to ask if it's ok to redistribute their docs on DevDocs, since their [docs repo](https://github.com/elastic/docs) mentions:

> The documents produced by this build process may be published only on http://www.elastic.co. They may not be published in any other form or on any other website without explicit permission.

Will merge when I hear back.

**Comment by 21xhipster** [comment]
Just discovered how to add elasticsearch to devdocs. And it's done :+1:! Cheers. Cross my fingers. Hope guys from Elastic also love devdocs!

**Comment by Thibaut** [comment]
No response :/

@yosiat would you mind shooting them an email? You might get more luck than me.

PS: I'm on vacation at the moment; will look at your other PRs within the next two weeks or so.

**Comment by yosiat** [comment]
Hi @Thibaut ,
Have they contacted you? what is the mail you sent to?

**Comment by Thibaut** [comment]
@yosiat I emailed info@elastic.co but they haven't replied…

**Comment by kimchy** [comment]
hey, as part of our agreement with o'reilly to make sure we can provide the book online for free is for it to only be allowed to be hosted on the elastic website. Same for our other docs as we plan to turn some of those into books as well.

**Comment by Thibaut** [comment]
@kimchy Thanks for the reply. If that changes in the future, feel free to get in touch and I'll be happy to add ES's docs to DevDocs.

**Comment by JaimeObregon** [comment]
Hi! It's eight years later and Elasticsearch repo still prohibits this integration.
I, like many, would really love Elasticsearch🤝DevDocs.
@kimchy, any update on this?

**Comment by Mohammadfazel03** [comment]
hey please add elastic search documantation

**Pull request closed without merging**
