### PR TITLE
Add Nim documentation

### PR DESCRIPTION
**Pull request by kosz78**
Add Nim documentation from https://nim-lang.org/docs/overview.html
Contains manuals, tutorials and all core modules documentation.
image

### CODE REVIEW

**Comment by j-f1** [comment]
It looks like you’re using the Jest logo instead of the Nim logo in the sidebar.

**Comment by kosz78** [comment]
I have added icons in `public/icons/docs/nim/16.png`

**Comment by Thibaut** [comment]
@kosz78 Thanks for the PR. I'll get this out soon.

**Comment by Thibaut** [comment]
Sorry for the delay. I'm on vacation for the next couple weeks. Aiming to work on this the weekend of Aug 27th or Sept 3rd.

**Comment by Thibaut** [comment]
Done :)
09eea66d5769c8427a7f8aa1a6f3903c934166c3 a4ba32ebcaa1a07e340bb992d4bb9eed578aad40
http://devdocs.io/nim/

**Pull request closed without merging**
