### PR TITLE
OpenJDK documentation

### PR DESCRIPTION
**Pull request by freayd**
As discussed in the issue #593, here comes the pull request regarding the OpenJDK documentation. This work is base on the previous #560, thanks @japborst.

The documentation is sourced from [openjdk-8-doc_8u121-b13-4_all.deb](https://packages.debian.org/sid/openjdk-8-doc). Only the subdirectoy `usr/share/doc/openjdk-8-jre-headless/api` was extracted.

I've tried to include all packages and it's working fine for me, I don't experience any slow down. They are 217 types and 46 084 entries in 4 733 files occupying 153 MB. I think many other packages than the ones proposed in #560 are useful, like `javax.xml`. What do you think @Thibaut?

The highlighting issue is solved. Unfortunately Prism remove all `<a>` links inside `<pre>` tags but I haven't looked much into it. I don't think it's a big problem thought.

The Java documentation contains a lot of duplicated information, typically a summary of all methods and further down detail explanations for these methods. I tried to remove all these duplicates so the resulting documentation is lighter and easier to read.

I have reused the logos from the request #560, but I think they might be copyrighted and I'm not sure they can be used in Devdocs. I don't see this logo on the [OpenJDK](http://openjdk.java.net/) and [IcedTea](http://icedtea.classpath.org/wiki/Main_Page) websites. And the logo used in the [Java Wikipedia article](https://en.wikipedia.org/wiki/Java_(programming_language)) seems to be subject to fair use.

### CODE REVIEW

**Comment by japborst** [comment]
Very nice! I like it :-)

**Comment by Thibaut** [comment]
Thanks for an outstanding PR @freayd (and @japborst for the original PR).

> I've tried to include all packages and it's working fine for me, I don't experience any slow down. They are 217 types and 46 084 entries in 4 733 files occupying 153 MB.

I'm not too worried about the speed of the search. Even with 100k entries it seems to be holding up pretty well (I did a lot of optimization a while back).

However, I'm worried about search results becoming noisy / less useful due to the 46k entries, and increasing the chance that users will hit the IndexedDB quota and lose their offline data (until browsers implement the [Storage Standard](https://storage.spec.whatwg.org/), all website data is unfortunately non-persistent and subject to deletion when e.g. the device is low on disk space).

Since I expect this doc will be used by a large number of users, we should optimize/polish it as much as we can. A good number to shoot for would be ~20k entries (IIRC the biggest doc we have today is Drupal 8, with 12k entries).

Is AWT still actively used? Packages like `java.rmi` and `javax.management` can probably be left out / not useful to most people. Packages like `javax.xml` and `javax.swing` could be extracted in separate doc versions (see docs like Haxe and Tensorflow), but let's first try to get the number down as much as we can.

> I have reused the logos from the request #560, but I think they might be copyrighted and I'm not sure they can be used in Devdocs. I don't see this logo on the OpenJDK and IcedTea websites. And the logo used in the Java Wikipedia article seems to be subject to fair use.

I don't think we should use the Java logo, since we're adding OpenJDK. Please remove the logo and I'll figure something out. Also, please rename the doc/scraper "OpenJDK".

**Comment by Kaijiro** [comment]
@Thibaut maybe should we split java packages into differents documentation, so Java AWT could be apart from "Java Core" (and some additionnal splits that we should think all together).

What do you think about it ?

**Comment by freayd** [comment]
Thanks all for your input.

I propose to split the documentation into four. Note that I counted only the processed HTML file sizes and not the index (db.json currently uses 74&nbsp;MB and index.json 6&nbsp;MB).

Group|Entries|Size|Packages
-------|-------|----|--------
Core|9 746|16 MB|java.io, java.lang, java.math, java.net, java.text, java.time, java.util
Tools|9 094|16 MB|java.beans, java.nio, java.security, javax.annotation, javax.crypto, javax.imageio, javax.lang, javax.management, javax.naming, javax.net, javax.print, javax.script, javax.security, javax.sound, javax.tools
GUI|18 145|26 MB|java.awt, javax.swing
Web|9 099|14 MB|java.applet, java.rmi, java.sql, javax.accessibility, javax.activation, javax.activity, javax.jws, javax.rmi, javax.sql, javax.transaction, javax.xml, org.ietf, org.omg, org.w3c, org.xml

We could combine Core and Tools which will be ~19k entries.
Swing actually relies on AWT, they are complementary so I put them together.
What do you think?

**Comment by Thibaut** [comment]
@freayd again, great work! 

FYI `db.json` is just all the HTML files combined into one. It's used for the offline mode (rather than make one request for each file, which would take forever, the app downloads the entire doc in one file/request). For offline mode, the size of a doc is `index.json` + `db.json`.

Seeing that "Tools" include things like print, sound, etc. I think it makes sense to keep it separate. But we should make sure there isn't too strong a dependency between "Core" and "Tools", or the split is counter-effective (if 99% of people end up enabling both). Do the packages in "Core" cover enough of the language that most people wouldn't enable "Tools"? We should include in "Core" everything that most people need most of the time.

**Comment by japborst** [comment]
@thibaut personally I think it's a fair split, but it remains subjective. Do you keep statistics of what people enable? If so, we could check and iterate once or twice.

**Comment by freayd** [comment]
I've pushed a couple of commits that split the documentation into four as we talked earlier.

I've also added a new filter called clean_urls which allows to maintain links between documentations which would have otherwise been dropped. They are a few edge cases thought where we can land on a "Page not found" after clicking an inter-documentation link even though the document actually exists (refreshing the page works).

I agree and also think it is subjective to choose how to split the documentation. I've been searching for statistics about package usage but couldn't find any, so I made up some. I researched in Github "import java.lang" and did it for every of the 39 "super" packages. It's no bullet proof (packages not imported but accessed by the full path aren't counted, GitHub also warns that code queries are subject to a timeout and might be incomplete) but at least it gives a rough idea. Here are the results with the current documentation split:

Group | Package | GitHub code results | DevDocs entries
----- | ------- | ------------------- | ---------------
Core | java.util | 84 293 604 | 4 243
Core | java.io | 42 617 769 | 698
Core | java.text | 32 966 855 | 478
Web | org.xml | 27 997 701 | 325
Core | java.time | 25 434 903 | 1 400
Core | java.net | 19 803 745 | 706
Core | java.lang | 17 964 441 | 2 092
Core | java.math | 11 303 298 | 129
Web | org.w3c | 11 157 594 | 396
Web | java.sql | 8 600 354 | 919
Tools | java.security | 8 556 922 | 1 177
GUI | java.awt | 8 492 022 | 5 766
Tools | javax.annotation | 6 920 679 | 73
GUI | javax.swing | 6 463 111 | 12 379
Web | javax.xml | 6 122 457 | 2 139
Tools | java.nio | 5 419 356 | 1 040
Tools | java.beans | 5 214 548 | 468
Tools | javax.print | 4 718 565 | 1 078
Tools | javax.net | 4 217 379 | 315
Tools | javax.lang | 3 504 900 | 433
Tools | javax.security | 2 700 837 | 359
Tools | javax.tools | 2 312 077 | 167
Web | javax.sql | 2 025 446 | 527
Web | org.ietf | 1 433 874 | 138
Web | javax.transaction | 1 315 190 | 64
Tools | javax.management | 1 064 609 | 1 532
Web | java.rmi | 920 072 | 296
Tools | javax.script | 731 676 | 127
Web | java.applet | 724 655 | 49
Tools | javax.crypto | 701 461 | 251
Tools | javax.naming | 700 389 | 619
Web | org.omg | 616 352 | 3 597
Tools | javax.imageio | 552 398 | 876
Web | javax.activity | 447 999 | 7
Web | javax.rmi | 354 132 | 92
Tools | javax.sound | 287 089 | 579
Web | javax.activation | 273 505 | 119
Web | javax.jws | 159 454 | 64
Web | javax.accessibility | 145 285 | 367

Although it is arbitrary, we might want to integrate the most used "Tools" packages into "Core", like the security related ones (**java.security, javax.security, javax.crypto**), the counterpart of the already "Core" packages (**java.nio, javax.net, javax.lang, javax.tools**) and maybe the other couple of widely used packages (**javax.annotation, java.beans**). In this case, "Core" will have 14&nbsp;029 entries and "Tools" 4&nbsp;811.

**Comment by Thibaut** [comment]
> Do you keep statistics of what people enable? If so, we could check and iterate once or twice.

I can extrapolate how popular a doc is based on page views tracked client-side, but I don't have precise stats on what people enable.

---

Great research @freayd. Let's remove the "Tools" package for now (put it all in "Core"). I'll try to trim the markup and reduce the no. of entries a bit more when I merge this, + do some performance testing.

I'm catching up with doc updates today, then traveling for a week, so won't be able to get this out before a couple weeks from now.

Please squash your commits, so I can cherry-pick locally (fits my workflow better than merging on github.com).

**Comment by freayd** [comment]
Sorry for the delay, it should be ready to merge now.

**Comment by freayd** [comment]
Sorry for the delay. I've merged Core & Tools and fixed a regression from the last commit. Should be ready to merge now.

**Comment by Thibaut** [comment]
Started working on this yesterday but didn't have time to finish. Will try to finish next week-end.

**Comment by Thibaut** [comment]
Done: f606c0abc8fce8c3e0379becfc264c01f1a726f6 2efce745210f354d4226cf78822791e5f9abad89 🎉 
http://devdocs.io/openjdk~8/
http://devdocs.io/openjdk~8_gui/
http://devdocs.io/openjdk~8_web/

I managed to reduce the size of the docs by ~30% by trimming the markup as much as possible.

I also removed "constructor" entries, since they always have the same name as the page's name, and "field" and "constant" entries, because from what I can tell most of them aren't very useful and they're located at the top of the page, so should be easy to find. Overall this reduces the number of entries by ~20%. I might re-add the "field" and "constant" entries if people ask for it and once I've had time to optimize the search some more (didn't have time to do it for this PR).

Thanks for the hard work!

**Comment by freayd** [comment]
Very nice job, many thanks ! 🎉

**Pull request closed without merging**
