### PR TITLE
Add Vulkan Documentation

### PR DESCRIPTION
**Pull request by theblackunknown**
Add Vulkan Documentation available:
- Either from https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html
- Or can be built from https://github.com/KhronosGroup/Vulkan-Docs

Not sure if scrapper is optimal, but I managed to re-create most of original structure.
I skipped the page about Vulkan Specification as I had problem with links, and also to lighten the amount of data, but that could be re-integrated.

I still haven't propose an icon yet even if official logos are available from Khronos website.
It is mentioned that they should not be used at a smaller siwe than 50px, so I am still looking for an alternative.

Last remark, Vulkan API Reference is a single-paged documentation.
I expected to have another scrapped documentation like this one but I could not find any examples, so feel free to suggest any improvements on it.  

vulkan-snapshot

### CODE REVIEW

**Comment by theblackunknown** [comment]
@j-f1 Thanks ! I thought the scrolling was strange, but actually all referred types refers to anchor to the same page !

Is is common to let the original CSS or should I migrate it to a uniform CSS ?

**Comment by j-f1** [comment]
All of the docs should use the same DevDocs CSS.

**Comment by Thibaut** [comment]
@theblackunknown thanks for the PR. I'm on vacation for the next couple weeks. I'll try to get this out the weekend of Aug 27th or Sept 3rd.

> Is is common to let the original CSS or should I migrate it to a uniform CSS ?

Don't worry about the CSS. I'll take care of it.

Please squash your commits so I can cherry-pick into `master` (fits my workflow better than merging on GitHub).

**Comment by theblackunknown** [comment]
@Thibaut Thanks for handling the CSS update, I'll check it how you do it for further documentations I want to add.
I have added a logo approved by Khronos Webmaster (SVG and original version included in case we want to re-generate icons)
All of this squashed into 1 commit if I haven't done any mistakes

**Comment by Thibaut** [comment]
> Thanks for handling the CSS update

It comes down to adding as little doc-specific CSS as possible, by cleaning up the markup (with proper `<h2>`, `<h3>`, `<p>`, `<code>`, `<ul>`, `<table>`, etc. and no unnecessary tags), so that it fits the [`simple`](https://github.com/Thibaut/devdocs/blob/master/assets/stylesheets/pages/_simple.scss) stylesheet. The more custom CSS per doc, the more difficult it becomes to maintain and change things over time. 

>  I have added a logo approved by Khronos Webmaster (SVG and original version included in case we want to re-generate icons)

Thanks! I downloaded both locally, so you can remove them from the commit. 

Where/how did you get approval?

>  All of this squashed into 1 commit if I haven't done any mistakes

Looking good 👍

**Comment by theblackunknown** [comment]
> It comes down to adding as little doc-specific CSS as possible, [...], so that it fits the simple 
> stylesheet. The more custom CSS per doc, the more difficult it becomes to maintain and change things
> over time.
Gotcha, I'll have a look on how you do that 

> Thanks! I downloaded both locally, so you can remove them from the commit.
> Where/how did you get approval?
I contacted the Khronos via their contact email directly, and I got approval there.
They said they approve the usage of the icon for now, while their marketing is review it.

I can forward you the email conversion if required

When I have the chance to use my computer I'll clean the commit

**Comment by theblackunknown** [comment]
I have now removed original icons from the pull request

**Comment by Thibaut** [comment]
Done :)
2f62bca5e4259d8dae045b3cf7be9173f1fa9b3d 0df3a7755887ed472df36164bebccfd1c275072d
http://devdocs.io/vulkan/

I made the scraper remove as much unnecessary markup as possible, given that the page is a whopping 2.2MB (1.7MB on DevDocs).

> I can forward you the email conversion if required

If you don't mind, send them a link to this PR/convo, and tell them to let us know here if DevDocs's use of their logo turns out not to be OK.

**Pull request closed without merging**
