### PR TITLE
Adding documentation for opentsdb

### PR DESCRIPTION
**Pull request by yosiat**
OpenTSDB 2.1 Documentation

### CODE REVIEW

**Comment by Thibaut** [comment]
Could you get confirmation from OpenTSDB that their docs are licensed under MIT license please. Their site says "© Copyright 2015, OpenTSDB" and their docs repo has no license file…

**Comment by tsuna** [comment]
I added the same license files as we use for OpenTSDB in the upstream repo: OpenTSDB/opentsdb.net@08559a19346649255b7a947ccac328f5668cbdde – the license is LGPLv2.1+, is that OK with you guys?

**Comment by Thibaut** [comment]
@tsuna that's perfect, thanks!

I'll try to get this merged in the next week or two.

**Comment by Thibaut** [comment]
Merged: f6df847e8659a2dfc05f36ccd1469fc46462ec61
Thanks!

**Pull request closed without merging**
