### PR TITLE
Twig 1.24.1 Documentation

### PR DESCRIPTION
**Pull request by compleatguru**
Just made it. Hope it is useful for all of us!

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks for your contribution. Please squash your commits in both your PRs. I'll take a look in the next week or so.

**Comment by compleatguru** [comment]
Please refer https://help.github.com/articles/about-pull-request-merges/

So it will be clean for the master branch with merge squash.

**Comment by Thibaut** [comment]
Merging PRs on github.com doesn't fit my workflow. I'll cherry-pick your commit into the master branch once you squash and I have time to take a look at it.

**Comment by compleatguru** [comment]
squash commits.
hope this is good for use.

**Comment by Thibaut** [comment]
Done: 6b0e60f65a08431c94a50e10c2aed0ce939c5e65 9ad721ed44dc48e3170f91eede854a435fa10e96
http://devdocs.io/twig/

**Pull request closed without merging**
