### PR TITLE
Add Chef documentation

### PR DESCRIPTION
**Pull request by doertedev**
Chef documentation from docs.chef.io
Should work so far. Haven't figured out with which command you generate the iconset though. Added the logo from the official logo download site (as stated in "SOURCE"). Also pinged a marketing person at chef which didnt respond yet.
Feedback pls

### CODE REVIEW

**Comment by doertedev** [comment]
[Issue](https://github.com/Thibaut/devdocs/issues/279)

**Comment by Thibaut** [comment]
Thanks for working on this. 

I'd like to include all pages in the docs, not just the "resource" pages. We also need to categorize the pages somehow (e.g. by their nav item in the sidebar: "Getting Started", "Theory & Concepts", etc.). This is done with the `get_type` function in `EntriesFilter`.

**Comment by doertedev** [comment]
Okay imma get on this over the week... Thanks for the support. I just wanted the resources for myself :) But the rest? Sure. Why not.

**Comment by doertedev** [comment]
[Docs](https://docs.chef.io/) << top left - "Filter by products and versions"
Now we most certainly want to only have the open source software documentation (for the scope of devdocs.io). So without the external software (ohai and so forth) that leaves us with the documentation for "chef client" and "chef server". Currently, this selection leaves us with [This docs for the client](https://docs.chef.io/release/12-5/) and [This docs url for the server](https://docs.chef.io/release/server_12-2/). Would you agree to split those into two main sections (e.g. scrapers) ?
Because I now have many skip_patterns, and yet I realized the external and/or commercial content is huge. But even those two main sections will include a large chunk of content. So I think splitting them would be a good idea. Ideas?

**Comment by doertedev** [comment]
There are 4 items which are missing the corresponding navigation items. Sorta added them by hand.
bildschirmfoto von 2015-11-13 18-12-02
Some navpoints are kinda long. Ideas? Or just merge?

**Comment by Thibaut** [comment]
Sorry for the delay.  I'll try to finish this next week-end.

Can you make the PR a single commit and not modify ` public/docs/docs.json` please.

**Comment by Thibaut** [comment]
@doertedev ping: https://github.com/Thibaut/devdocs/pull/282#issuecomment-157032285

**Comment by RC1140** [comment]
@Thibaut / @doertedev  Can I volunteer to do the cleanup here so that this can get merged ?

**Comment by doertedev** [comment]
Please do so. Switched to a startup so my time for foss is nonexistent :(

**Comment by RC1140** [comment]
Done (https://github.com/Thibaut/devdocs/pull/358)

**Comment by Thibaut** [comment]
Done: http://devdocs.io/chef/
0948b5882ed140968d2545db63941ea16c6bf4a8 1fa82430b0caadb787301f02a1e2e47f3e26377e 
Thanks for the help @RC1140

**Pull request closed without merging**
