### PR TITLE
Add Tcl/Tk documentation

### PR DESCRIPTION
**Pull request by tbsmark86**
All commands without extension C-API. No fancy style or anything.

Without C-API to keep size small and it's only required to extend the language not to use it.
I did not remove the copyright list because each page has a specific list.

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks! I'll try to look at this next week-end. How did you get the docs to run on localhost?

**Comment by tbsmark86** [comment]
Just a simple mirror:
  wget -k -p -np -nH --cut-dirs=1 -r -l 10 -np http://www.tcl.tk/man/tcl/
And a LAMP Stack

**Comment by Thibaut** [comment]
Sorry for the delay. I haven't had much time to work on DevDocs lately and can't for the next 2 weeks. Will try to get this out next month.

**Comment by Thibaut** [comment]
Merged:

**Comment by Thibaut** [comment]
Merged:
ae7a5abd96892f1c641aabd710d188e4cae22992
23ebf25bcb3c284ec7c1e58ba93c782ee0c9b64c
http://devdocs.io/tcl_tk/
Thanks for the PR!

**Pull request closed without merging**
