### PR TITLE
Add CakePHP Documentation

### PR DESCRIPTION
**Pull request by scherepn**
A zip archive of the documentation is available at:
http://api.cakephp.org/3.1/cakephp-api-documentation.zip

All CakePHP code and documentation are available under the MIT License, but the small logo/icon is available under the CC-BY-NC-ND. I looked, but was unable to find a non-NC version of the logo. If you need an exception, you can contact legal [at] cakefoundation.org.

The documentation HTML was a bit messy. I documented clean_html as best as I could.

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks! Sorry for the delay. I haven't had much time to work on DevDocs lately and can't for the next 2 weeks. Will try to get this out next month.

**Comment by run-time** [comment]
Hi @scherepn thanks for adding this documentation.  I've checked out this PR locally and get this error when trying to install...

```
FH1007771-MBP:devdocs ctrpapa$ thor docs:download --all
(1/82) Bower OK
(2/82) Backbone.js OK
(3/82) CakePHP FAILED (OpenURI::HTTPError: 404 Not Found)
...
```

did something move?

**Comment by Thibaut** [comment]
@run-time the doc will only be available via `thor docs:download` once this PR is merged and I upload the files to DevDocs's server. In the meantime you can try out the scraper using `thor docs:generate`, but that'll require downloading the source doc locally and changing the `dir` [here](https://github.com/scherepn/devdocs/blob/1d154dffabf1e3c697d45d31164ec4a8b8b070fd/lib/docs/scrapers/cakephp.rb#L6).

**Comment by Thibaut** [comment]
Done: http://devdocs.io/cakephp/
26bead24b49779836fe054c158686f4c50fdb7dd 5f2d9cde50d94a8d5afcb954b11a52e407b2a326 

Great PR, thanks!

**Pull request closed without merging**
