### PR TITLE
Add Laravel 5.5 documentation

### PR DESCRIPTION
**Pull request by m1guelpf**
ping @Thibaut

### CODE REVIEW

**Comment by Thibaut** [comment]
This doesn't work at the moment because the 5.5 API docs haven't been published yet ( https://laravel.com/api/5.5/ → 404).

Waiting on https://github.com/laravel/docs/issues/3585.

**Comment by m1guelpf** [comment]
@Thibaut The API is published now...

**Comment by Thibaut** [comment]
I'll publish them on DevDocs this week-end.

**Comment by Thibaut** [comment]
Done in 6cbf550ec82999fd21703495a59dc49e175703c0.

**Pull request closed without merging**
