### PR TITLE
Immutablejs

### PR DESCRIPTION
**Pull request by yosiat**
As discussed in: https://trello.com/c/5q0d0153/223-immutable-js

It works right now, some notes:
- I will squash the commits together, once it passes review.
- I have type pages for example "fromJS" with one children "fromJS" which looks weird, I have no idea how to solve it.

**Important: changes in scrapper.rb:**
- Add support for passing regex as stub url parameters
- Pass the stubbed url to the block (if you have generic stubber, you will need the url)

**Scrapping note:**
The chosen approach might be slow to scrap, but I think if we will change marionette to headless brwoser like phantomjs/webkit it will be much faster (I can submit PR later, if wanted).

### CODE REVIEW

**Comment by Thibaut** [comment]
Thanks for the PR. I'll try to take look next week-end.

Please squash your commits now. Makes it easier to test (and I may end up finishing the scraper rather than reviewing here — sorry I don't have much time for DevDocs these days).

**Comment by yosiat** [comment]
@Thibaut Hi!
I will squash the commits ASAP.

What do you mean by you end up finish the scrapper? did you wrote scrapper for immutable?

**Comment by Thibaut** [comment]
> What do you mean by you end up finish the scrapper? did you wrote scrapper for immutable?

I didn't. I meant that I may end up merging your commit and making changes to it right after, instead of asking you to update your PR.

**Comment by yosiat** [comment]
@Thibaut oh! ok!

Squashed the commits! If you have any questions/changes to be made, I am available 👍

**Comment by yosiat** [comment]
@Thibaut  any status? have you looked at code already? is everything ok?

**Comment by Thibaut** [comment]
Haven't had time yet, sorry.

**Comment by lshaf** [comment]
waiting for this one 😄

**Comment by Thibaut** [comment]
The current code doesn't work for me (Selenium/Firefox doesn't load any page) and although this is a great effort, I don't like the approach, because it requires too many hacks and will be hard to maintain in the long run.

I started working on an alternative that loads a single page and clicks the sidebar links to generate all the content. I haven't had time to finish it today but will try next week-end. I'll leave this PR open until the doc is done.

Thanks again for the hard work and sorry if I don't end up using your code.

**Pull request closed without merging**
